#!/usr/bin/env bash

#!/bin/bash

# Array of alias names to be unalias
alias_names=("e" "esudo") # Add your alias names here
# Loop through each alias to unalias them
for alias_name in "${alias_names[@]}"; do
  # Check if the alias exists
  if alias "$alias_name" &>/dev/null; then
    # If the alias exists, unalias it
    unalias "$alias_name"
  fi
done

# -- e --: edit in $EDITOR
e() {
  if [ ! "$1" ]; then
    fzf --multi --bind "enter:become($EDITOR {})"
    return
  fi
  if [ -e "$1" ]; then
    "$EDITOR" "$1"
  else
    dir=$(zoxide query "$1")
    if [ -d "$dir" ]; then
      cd "$dir" && fzf --multi --bind "enter:become($EDITOR {})"
    else
      $EDITOR "$1"
    fi
  fi
}

esudo() {
  if [ ! "$1" ]; then
    fzf --multi --bind "enter:become(sudo -E $EDITOR {})"
    return
  fi
  if [ -e "$1" ]; then
    sudo -E $EDITOR "$1"
  else
    dir=$(zoxide query "$1")
    if [ -d "$dir" ]; then
      cd "$dir" && fzf --multi --bind "enter:become(sudo -E $EDITOR {})"
    else
      sudo -E "$EDITOR" "$1"
    fi
  fi
}

# nvim/vim alias
# nvim() {
# 	if [ $# -eq 0 ]; then
# 		command nvim +"Lex" "$(pwd)"
# 	else
# 		command nvim "$@"
# 	fi
# }
#
# vim() {
# 	if [ $# -eq 0 ]; then
# 		command nvim +"Ex" "$(pwd)"
# 	else
# 		command nvim "$@"
# 	fi
# }

# Find in file using ripgrep
rgf() {
  ROOT_PATH="${1:-.}"
  RG_DEFAULT_COMMAND="rg -l --smart-case --hidden --no-follow -g '!{.git,node_modules}'"
  FZF_DEFAULT_COMMAND="rg --files $ROOT_PATH" fzf \
    -m \
    -e \
    --ansi \
    --phony \
    --bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
    --preview "batgrep --color --context 5 {q} {1}" | cut -d":" -f1,2
}

rgfe() {
  result=$(rgf "$@")
  [[ -n "$result" ]] && "$EDITOR" "$result" || return
}

ff() {
  result=$(fzf "$@")
  [[ -n "$result" ]] && "$EDITOR" "$result" || return
}

function y() {
  local tmp
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd" || exit
  fi
  rm -f -- "$tmp"
}

function yf() {
  local tmp
  tmp="$(mktemp -t "yazi-chooser.XXXXXX")"
  yazi "$@" --chooser-file="$tmp"
  if f="$(command cat -- "$tmp")" && [ -n "$f" ]; then
    echo "$f"
  fi
  rm -f -- "$tmp"
}

# Display audio visualizer with glava
# while choosing/change glava backend source
viz() {
  source=$(pactl list sinks short | awk '{print $2}' | fzf)
  sed -i "s/^\(#request setsource\) \"[^\"]*\"/\1 \"$source.monitor\"/" ~/.config/glava/rc.glsl
  pkill glava &>/dev/null
  glava --desktop &>/dev/null &
  disown
}

calc() {
  rofi -show calc -modi calc
}

sysinfo() {
  neofetch --ascii "$HOME/.config/neofetch/arch-ascii-2"
  task 2>/dev/null
}
